### ISSUE TITLE
How do i apply a .frag shader?

### ISSUE THREAD

**Issue by DybaTubeYT1** [oatmealine/notitg-shaders#1]
I try using .frag shader but this happens:
![image](https://user-images.githubusercontent.com/80713813/195171237-df355526-c003-4268-9625-4255f16f595e.png)

**Comment by oatmealine** [comment]
this feels like an error with your gpu - besides, this is not the place for this kind of issue, and i'm not sure how much support i can offer

**Comment by DybaTubeYT1** [comment]
then where i put this? (Im using .frag, not .vert)

**Comment by DybaTubeYT1** [comment]
On the function: P[1]:SetArrowShader(myVertAux:GetShader())

On the layer: <Layer Type="Aux" Vert="shaders/fisheye.frag" Name="myVertAux" />

Is this how to use a frag?

**Comment by DybaTubeYT1** [comment]
nvm i fixed it
